apiVersion: v1
kind: Pod
metadata:
  name: limited-pod
  namespace: dev-ns
spec: 
  containers:
    - name: busybox-container
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"